 version: "3.5"
 services:
   mongo-orion:
    container_name: mongo-orion
    image: mongo:3.6
    command: --nojournal
    ports:
     - "27017:27017"

   mongo-data:
    container_name: mongo-data
    image: mongo:3.6
    command: bash -c "sh /tmp/resources/import_distances.sh"
    depends_on: 
      - orion
    volumes:
      - ./:/tmp

   orion:
    image: fiware/orion
    links:
      - mongo-orion
    ports:
      - "1027:1026"
    depends_on: 
      - mongo-orion
    command: -dbhost mongo-orion

   web:
     image: ging/python-flask
     container_name: web
     environment:
       - PROJECT_HOME=./
     depends_on: 
      - orion
     command: bash -c "sleep 10 && python3 /resources/web/predict_flask.py"
     ports:
      - "5000:5000"
     volumes:
       - ./resources:/resources

   script:
     image: ging/python-flask
     container_name: script
     depends_on: 
      - orion
     healthcheck:
      test: ["CMD", "curl", "-f", "http://orion:1026"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
     command: bash -c "sh /resources/entities/createEntities.sh && sh /resources/entities/createSubscriptions.sh"
     volumes:
       - ./resources:/resources

   script-draco:
     image: ging/python-flask
     container_name: script-draco
     environment:
      - DRACO_ENDPOINT=draco:9090
     depends_on: 
      - draco
     healthcheck:
      test: ["CMD", "curl", "-f", "http://draco:9090/nifi-api/system-diagnostics"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 140s
     command: bash -c "sleep 10 && python3 /resources/entities/runDraco.py"
     volumes:
       - ./resources:/resources

   draco:
    image: ging/fiware-draco
    container_name: draco
    depends_on:
      - orion
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    ports:
      - "9090:9090"
      - "5050:5050"

   spark-master:
     image: bde2020/spark-master:3.0.0-hadoop3.2
     container_name: spark-master
     ports:
       - "8080:8080"
       - "7077:7077"
       - "9001:9001"
     depends_on:
       - web
     environment:
       - INIT_DAEMON_STEP=setup_spark
       - "constraint:node==spark-master"
     command: bash -c "sh /flight_prediction/flight_prediction/run-spark-jobs.sh"
     volumes:
       - ./:/flight_prediction

   spark-worker-1:
     image: bde2020/spark-worker:3.0.0-hadoop3.2
     container_name: spark-worker-1
     depends_on:
       - spark-master
     ports:
       - "8081:8081"
     environment:
       - "SPARK_MASTER=spark://spark-master:7077"
       - "constraint:node==spark-master"
  
